# pwd = "????"
# count =1
# while pwd!="1111" and count<=3:
#     pwd = input("비밀번호 입력하세요: ")
#     count = count+1
# if pwd == "1234":
#     print("비밀번호가 정확합니다")
# elif count>3:
#     print("비밀번호를 3번 잘못 입력했습니다.")

# s = 1
# n = 1
# while s <10:
#     s=s+n
#     print("s=", s)


# x = 1.0
# y = 1.0
# i = 0
# while y<=1.5:
#     x=x/2
#     y=x+y
#     i=i+1
#     print("x=", x)
#     print("y=", y)
# print("i=", i)
# #왜 i가 1이 아니고 2지?

num = int(input("정수의 개수: "))
while num <= 0:
    num=input("정수의 개수: ")
#어떨 때 어떤 변수를 몇개를 써야할지 모르겠다!